services:
  - type: web
    name: toc-graphviz-backend
    env: docker
    plan: free
    region: oregon
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PYTHONUNBUFFERED
        value: '1'
    autoDeploy: true
