services:
  - type: web
    name: toc-project
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt && apt-get update && apt-get install -y graphviz"
    startCommand: "python app.py"
    envVars:
      - key: PORT
        value: 10000
